#!/usr/bin/python

"""The Limine OS entry check must follow TARGET_OS_NAME, not a brand string.

The installer asserted that /boot/limine.conf contained the literal text
"Omarchy", which held only while the runtime package's template and its
limine-entry-tool config still used that name. Renaming the product made a
correctly generated boot entry fail finalization. These tests pin the check to
the entry limine-entry-tool actually writes, keyed by TARGET_OS_NAME.
"""

import json
import sys
import tempfile
import types
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "configs/airootfs/usr/share/omarchy-iso"))

sys.modules.setdefault(
    "orchestrator.archinstall_adapter",
    types.ModuleType("orchestrator.archinstall_adapter"),
)

from orchestrator import phases_impl  # noqa: E402

# A real limine.conf as limine-entry-tool writes it: the OS entry opens with a
# /+<TARGET_OS_NAME> header and repeats the name in a comment line.
LIMINE_CONF = """\
### Read more at config document: https://github.com/limine-bootloader/limine
default_entry: 2
interface_branding: Unbloarchy Bootloader
/+Unbloarchy
### This OS entry is auto-generated by limine-entry-tool
comment: Unbloarchy
comment: machine-id=ea41e012ec83456cb8ba2c5a64eeacd0 order-priority=50
  ### This kernel entry is auto-generated by limine-entry-tool
  comment: Kernel version: 7.0.10-arch1-1
  protocol: efi
  path: boot():/EFI/Linux/unbloarchy_linux.efi
  cmdline: root=/dev/mapper/root rootflags=subvol=@ rw rootfstype=btrfs
"""


class LimineOsEntryTest(unittest.TestCase):
    def test_finds_entry_named_by_target_os_name(self):
        self.assertTrue(phases_impl._limine_os_entry_exists(LIMINE_CONF, "Unbloarchy"))

    def test_still_finds_an_upstream_named_entry(self):
        # The ISO installs upstream runtime packages too, so the check cannot
        # assume the Unbloarchy spelling.
        upstream = LIMINE_CONF.replace("Unbloarchy", "Omarchy")
        self.assertTrue(phases_impl._limine_os_entry_exists(upstream, "Omarchy"))

    def test_rejects_a_config_missing_the_entry(self):
        self.assertFalse(phases_impl._limine_os_entry_exists(LIMINE_CONF, "Nonexistent"))

    def test_rejects_a_half_written_entry(self):
        # limine-entry-tool locates its own entry by the comment line, so an
        # entry missing either half did not survive its own next run.
        self.assertFalse(phases_impl._limine_os_entry_exists("/+Unbloarchy\n", "Unbloarchy"))
        self.assertFalse(phases_impl._limine_os_entry_exists("comment: Unbloarchy\n", "Unbloarchy"))

    def test_does_not_match_a_name_as_a_regex(self):
        # TARGET_OS_NAME is arbitrary config text; unescaped it would let a name
        # with a regex metacharacter match an unrelated entry.
        self.assertFalse(phases_impl._limine_os_entry_exists("/+a.c\ncomment: a.c\n", "abc"))

    def test_brand_string_alone_is_not_an_entry(self):
        # The regression: branding in the header is not what proves the entry.
        branding_only = "interface_branding: Unbloarchy Bootloader\n"
        self.assertFalse(phases_impl._limine_os_entry_exists(branding_only, "Unbloarchy"))

    def test_resolves_os_name_from_limine_entry_tool_config(self):
        config_text = 'TARGET_OS_NAME="Unbloarchy"\nCUSTOM_UKI_NAME="unbloarchy"\n'
        self.assertEqual(
            phases_impl._limine_setting(config_text, "TARGET_OS_NAME", "Omarchy"), "Unbloarchy"
        )

    def test_falls_back_when_the_config_does_not_set_it(self):
        self.assertEqual(phases_impl._limine_setting("", "TARGET_OS_NAME", "Omarchy"), "Omarchy")


class FinalizeLimineBootTest(unittest.TestCase):
    """End-to-end on the phase that failed, not just on the helper.

    The bug was an assertion inside finalize_limine_boot, so testing the
    helper alone cannot tell whether the phase still rejects a config.
    """

    def _context(self, root, limine_text, os_name):
        (root / "usr/bin").mkdir(parents=True)
        (root / "usr/bin/limine-update").write_text("#!/bin/sh\n")
        (root / "etc/default").mkdir(parents=True)
        (root / "etc/default/limine").write_text(
            'ESP_PATH="/boot"\nKERNEL_CMDLINE[default]+="@@CMDLINE@@"\n'.replace(
                "@@CMDLINE@@", "root=/dev/mapper/root rw"
            )
        )
        (root / "etc/snapper/configs/root").mkdir(parents=True)
        (root / "boot").mkdir()
        (root / "boot/limine.conf").write_text(limine_text)
        if os_name is not None:
            (root / "etc/limine-entry-tool.d").mkdir(parents=True)
            (root / "etc/limine-entry-tool.d/unbloarchy-defaults.conf").write_text(
                f'TARGET_OS_NAME="{os_name}"\n'
            )

        ctx = types.SimpleNamespace(
            target=root,
            omarchy_path=root / "usr/share/omarchy",
        )
        return ctx

    def _run(self, limine_text, os_name):
        from contextlib import ExitStack
        from unittest import mock

        with tempfile.TemporaryDirectory() as tmp:
            ctx = self._context(Path(tmp), limine_text, os_name)
            with ExitStack() as stack:
                stack.enter_context(
                    mock.patch.object(phases_impl.subprocess, "run")
                )
                phases_impl.finalize_limine_boot(ctx)

    def test_accepts_a_renamed_entry(self):
        # The regression: this raised "has no Omarchy entry" on a correct install.
        self._run(LIMINE_CONF, "Unbloarchy")

    def test_accepts_an_upstream_named_entry(self):
        self._run(LIMINE_CONF.replace("Unbloarchy", "Omarchy"), "Omarchy")

    def test_rejects_a_config_with_no_entry_at_all(self):
        with self.assertRaisesRegex(RuntimeError, "has no Unbloarchy entry"):
            self._run("default_entry: 2\n", "Unbloarchy")


class ValidateBootEntryTest(unittest.TestCase):
    """validate_boot repeats the entry check four phases later.

    Fixing only finalize_limine_boot would pass the failing phase and then stop
    the install again at "Validating boot setup", so both call sites are pinned.
    """

    def _context(self, root, limine_text, os_name):
        (root / "etc/default").mkdir(parents=True)
        (root / "etc/default/limine").write_text(
            'ESP_PATH="/boot"\nKERNEL_CMDLINE[default]+="root=/dev/mapper/root rw"\n'
        )
        (root / "etc/limine-entry-tool.d").mkdir(parents=True)
        (root / "etc/limine-entry-tool.d/unbloarchy-defaults.conf").write_text(
            f'TARGET_OS_NAME="{os_name}"\n'
        )
        (root / "boot").mkdir()
        (root / "boot/limine.conf").write_text(limine_text)
        (root / "etc/kernel").mkdir(parents=True)
        (root / "etc/kernel/cmdline").write_text("root=/dev/mapper/root rw\n")
        return types.SimpleNamespace(
            target=root,
            omarchy_path=root / "usr/share/omarchy",
            encrypt=False,
            user_configuration={},
            is_protected=False,
            defer_provisioning=False,
            state={},
        )

    def _run(self, limine_text, os_name):
        from contextlib import ExitStack
        from unittest import mock

        with tempfile.TemporaryDirectory() as tmp:
            ctx = self._context(Path(tmp), limine_text, os_name)
            with ExitStack() as stack:
                for name in ("_assert_boot_hooks_restored", "_validate_kernel_headers"):
                    stack.enter_context(mock.patch.object(phases_impl, name))
                stack.enter_context(
                    mock.patch.object(phases_impl, "_boot_intent", return_value={"esp_mount": "/boot"})
                )
                stack.enter_context(mock.patch.object(phases_impl, "_storage_intent", return_value={}))
                stack.enter_context(mock.patch.object(phases_impl.arch, "has_uefi", return_value=False, create=True))
                phases_impl.validate_boot(ctx)

    def test_accepts_a_renamed_entry(self):
        self._run(LIMINE_CONF, "Unbloarchy")

    def test_rejects_a_config_with_no_entry_at_all(self):
        with self.assertRaisesRegex(RuntimeError, "has no Unbloarchy entry"):
            self._run("default_entry: 2\n", "Unbloarchy")


class ManifestEntryTest(unittest.TestCase):
    def test_recorded_install_has_a_detectable_entry(self):
        # The recorded Omarchy install is the only full limine.conf this repo
        # carries, so it is the one fixture proving the shape above is real.
        manifest = ROOT / "manifests/fresh-4-semantic.json"
        if not manifest.exists():
            self.skipTest("recorded install manifest not present")
        recorded = json.loads(manifest.read_text())
        text = recorded["files"]["boot"]["/boot/limine.conf"]["text"]
        self.assertTrue(phases_impl._limine_os_entry_exists(text, "Omarchy"))


if __name__ == "__main__":
    unittest.main()